version: "3.9"

# VSCode remote container tutorials:
  # https://code.visualstudio.com/docs/remote/create-dev-container#_set-up-a-folder-to-run-in-a-container
  # https://code.visualstudio.com/remote/advancedcontainers/connect-multiple-containers

  # "ports" vs. "expose": https://stackoverflow.com/a/40801773/5732518

services:

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: api
    volumes:
      - ./common:/app/common
      - ./api:/app
      - api-bashhistory:/commandhistory # Persist bash history
    env_file:
      - .env
    command: tail -f /dev/null # keep shell attached
    depends_on:
      - mongo

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: worker
    volumes:
      - ./common:/app/common
      - ./worker:/app
      - worker-bashhistory:/commandhistory # Persist bash history
    env_file:
      - .env
    command: tail -f /dev/null # keep shell attached
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  flower:
    image: mher/flower
    container_name: flower
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    ports:
      - 5555:5555
    depends_on:
      - redis

  mongo:
    image: mongo:5
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - ./mongo_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    expose:
      - 27017
    ports:
      - 27017:27017

volumes:
  worker-bashhistory:
  api-bashhistory: